# Generated by Django 4.0.3 on 2022-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.CharField(max_length=200)),
                ('split_files', models.CharField(max_length=200)),
                ('grade_folder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=200)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
    ]
